config/routes.rb
Rails.application.routes.draw do
  devise_for :guilds
  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/guild.rb
class Guild < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/member.rb
class Member < ApplicationRecord
  validates :m_name,presence: true,length: {maximum: 10},uniqueness: true
  validates :role,presence: true
  validates :job,presence: true,length: {maximum: 10}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
    @members = Member.order(role: :asc)
  end

  def show
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to members_path, notice: 'メンバー情報を追加しました！.' }
        format.json { render :index, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_path, notice: 'メンバー情報を更新しました！' }
        format.json { render :index, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'メンバー情報を削除しました！' }
      format.json { head :no_content }
    end
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:m_name, :role, :job, :sub_job)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SINoMyGuild</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <div class = "flash">
        <%= notice %>
      </div>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% flash.each do |key, value| %>
      <div class="flash">
        <%= content_tag(:div, value, class: "#{key}") %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= member.errors.count %>件のエラー</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :m_name,"Name" %>
    <%= form.text_field :m_name, id: :member_m_name %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.radio_button :role,0 %> 前衛
    <%= form.radio_button :role,1 %> 後衛
  </div>

  <div class="field">
    <%= form.label :job,"Main job" %>
    <%= form.text_field :job, id: :member_job %>
  </div>

  <div class="field">
    <%= form.label :sub_job %>
    <%= form.text_field :sub_job, id: :member_sub_job %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/edit.html.erb
<h1>メンバー情報を編集</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ギルドメンバーリスト</h1>

<table>
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Role</th>
      <th>Job</th>
      <th>Nightmare</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each.with_index(1) do |member,idx| %>
      <tr>
        <td><%= idx %></td>
        <td><%= member.m_name %></td>
        <% if member.role == 0 %>
          <td><%= "前衛" %></td>
        <% else %>
          <td><%= "後衛" %></td>
        <% end %>
        <td><%= member.job %></td>
        <td>メインナイトメア</td>
        <td><%= link_to '詳細', member %></td>
        <td><%= link_to '編集', edit_member_path(member) %></td>
        <td><%= link_to '削除', member, method: :delete, data: { confirm: '消去してもいいですか? 必要な場合はパスワード変更を忘れずに!' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- 15人までの制限でnew出来なくする -->
<% if @members.count < 15 %>
  <%= link_to 'メンバー情報を追加する', new_member_path %>
<% else %>
  <%= 'フルメンバー!' %>
<% end %>

app/views/members/new.html.erb
<h1>メンバー情報を追加</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<h1>メンバー詳細</h1>

<p>
  <strong>Name:</strong>
  <%= @member.m_name %>
</p>

<p>
  <strong>Role:</strong>
  <% if @member.role == 0 %>
    <td><%= "前衛" %></td>
  <% else %>
    <td><%= "後衛" %></td>
  <% end %>
</p>

<p>
  <strong>Main Job:</strong>
  <%= @member.job %>
</p>

<p>
  <strong>Sub job:</strong>
  <%= @member.sub_job %>
</p>

<%= link_to '編集', edit_member_path(@member) %> |
<%= link_to 'メンバーリストへ戻る', members_path %>